"""add_current_operator_id

Revision ID: 4de55a9c3132
Revises: 0bede434a900
Create Date: 2024-10-20 01:25:03.993174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de55a9c3132'
down_revision: Union[str, None] = '0bede434a900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('windows', sa.Column('current_operator_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('windows', 'current_operator_id')
    # ### end Alembic commands ###
