"""add services

Revision ID: 50aa8595872a
Revises: 9990a33f20a0
Create Date: 2024-10-19 16:10:24.580141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50aa8595872a'
down_revision: Union[str, None] = '9990a33f20a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('window_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('window_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['window_id'], ['windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('window_services')
    # ### end Alembic commands ###
